version: "3"

services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
        #entrypoint: ["./entrypoint.sh"]
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - grafana-dashboard
      - influx-db
    restart: always

  telegraf:
    image: telegraf:1.27.2
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var:/hostfs/var:ro
      - /run:/hostfs/run:ro
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - influx-db
    restart: always

  grafana:
    image: grafana/grafana:10.0.3-ubuntu
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - grafana-dashboard
    restart: always

networks:
  influx-db:
  grafana-dashboard:

volumes:
  grafana-storage:
  influxdb-storage:
